### ISSUE TITLE
ico wizard issue

### ISSUE THREAD

**Issue by lytlejustin0421** [poanetwork/ico-wizard#414] opened 2017-12-25 00:53 UTC
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

main net

### If you were able to create it, what is the URL of your crowdsale?

no

### Do you have screenshots showing the problem?

yes

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

![screenshot 2](https://user-images.githubusercontent.com/34811228/34329954-a209880c-e8d9-11e7-95d9-741630bea694.png)

here is all the field info i entered

name : Crypto Growth Fund
ticker: CGF
Decimals :18

i did 5 tiers

 Pre ico
start : 01/27/2018 12:00 pm    stop:01/28/2018 12:00am
max cap: 500000
rate :1350
wallet address: 0x2A812A3EF1c5A6149Ef8Fad870CAc3CD48096A52

ico round 1
start:02/03/2018 12:00pm stop: 02/04/2018 12:00pm
 max cap: 1500000
rate :1025

ico round 2
start:02/10/2018 12:00pm stop:02/11/2018 12:00pm
max cap: 1000000
rate : 825

ico round 3
start:02/17/2018 12:00pm stop:02/18/2018 12:00pm
max cap: 1000000
rate :625

ico round 4
start:02/24/2018 12:00pm stop:02/25/2018 12:00pm
max cap: 1000000
rate :425

compiler version 0.4.11
contract name: Mintedtokencappedcrowdsaleext
optimized true
min cap: 200

**Comment by igorbarinov** [comment] 2017-12-25 18:15
@lytlejustin0421 thank you, we will try to reproduce it and will return back to you

**Comment by lytlejustin0421** [comment] 2017-12-26 01:12
are you reproducing the token or doing the refund? i forgot to send the calculated amount

**Comment by igorbarinov** [comment] 2017-12-26 03:06
first, we need to reproduce it. today is a holiday so likely it will be tomorrow

**Comment by fvictorio** [comment] 2018-01-24 15:18
I couldn't reproduce this. Closing it for the moment, we can re-open it if something like this happens again.

**Closed by fvictorio** 2018-01-24 15:18 UTC
